name: Code Coverage

on:
  [push, pull_request]
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Jest Coverage Comment
        uses: MishaKav/jest-coverage-comment@v1.0.20
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          coverage-summary-path: ./coverage/coverage-summary.json
          title: Jest Coverage Comment
          summary-title: Summary
          badge-title: Coverage
          hide-comment: false
          create-new-comment: false
          hide-summary: false
          junitxml-title: JUnit
          junitxml-path: ./coverage/junit.xml
          coverage-title: Coverage
          coverage-path: ./coverage/coverage.txt


