name: Code Coverage

on:
  [push, pull_request]
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Jest coverage report
        uses: ArtiomTr/jest-coverage-report-action@v2.1.2
        with:
          coverage-file: ./coverage/coverage-final.json
