name: Code Coverage

on:
  [push, pull_request]
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn
        
      - name: Jest coverage report
        uses: ArtiomTr/jest-coverage-report-action@v2.1.2
        with:
          threshold: 80
