name: PR CI Workflow

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']
jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn

      - name: Run ESLint
        run: yarn lint
